apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mtgo-bot-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: mtgo-bot-pv
  resources:
    requests:
      storage: 10Gi
