apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mtgo-card-images-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: mtgo-card-images-pv
  resources:
    requests:
      storage: 20Gi
