apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mtgo-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: mtgo-postgres-pv
  resources:
    requests:
      storage: 10Gi
