apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mtgo-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: mtgo-logs-pv
  resources:
    requests:
      storage: 1Gi
