apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mtgo-sdk-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: mtgo-sdk-pv
  resources:
    requests:
      storage: 5Gi
