apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mtgo-wine-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: mtgo-wine-pv
  resources:
    requests:
      storage: 10Gi
