apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value:
        - name: ghcr-pull
  target:
    kind: Deployment
images:
- name: local/meta-stats
  newName: ghcr.io/mtgometastats/meta-stats
  newTag: 2b8c1f48969b2ca4e32f375dcea481fa94035f6c
- name: local/mtgosdk
  newName: ghcr.io/mtgometastats/mtgo-bot
  newTag: dbfeb12d655a5131851a72143d337edc4ff37760
- name: postgres
  newName: postgres
  newTag: "16"
