apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value:
        - name: ghcr-pull
  target:
    kind: Deployment
images:
- name: local/meta-stats
  newName: ghcr.io/mtgometastats/meta-stats
  newTag: 214c9fef2a39679539263d39165fc9abac1c9e02
- name: local/mtgosdk
  newName: ghcr.io/mtgometastats/mtgo-bot
  newTag: 3194b73b36cdaeac0c3517ef7d072337a5c7dc95
- name: postgres
  newName: postgres
  newTag: "16"
