apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: local/meta-stats
  newName: ghcr.io/mtgometastats/meta-stats
  newTag: 636413b1bbd4b109ae2f8badff3f6fb66f932c10
- name: local/mtgosdk
  newName: videreproject/mtgosdk
  newTag: headless
- name: postgres
  newName: postgres
  newTag: "16"
