apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-batalhanaval-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: minecraft-batalhanaval-pv
  resources:
    requests:
      storage: 10Gi
