apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: ghcr-pull
    target:
      kind: Deployment
      name: second-star-api
  - patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: ghcr-pull
    target:
      kind: Deployment
      name: second-star-web
images:
  - name: local/second-star-merlin
    newName: ghcr.io/mfjess/second-star-merlin
    newTag: latest
  - name: local/second-star-encanto
    newName: ghcr.io/mfjess/second-star-encanto
    newTag: latest
  - name: postgres
    newName: postgres
    newTag: "16"
