apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-disneybros
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft-disneybros
  template:
    metadata:
      labels:
        app: minecraft-disneybros
    spec:
      nodeSelector:
        kubernetes.io/hostname: dentrodoarmario
      containers:
        - name: mc
          image: itzg/minecraft-server:latest
          stdin: true
          tty: true
          env:
            - name: EULA
              value: "true"
            - name: TYPE
              value: "FABRIC"
            - name: MEMORY
              value: "6G"
            - name: VERSION
              value: "26.2"
            - name: MOTD
              value: "DisneyBros mc server 26.2 9/9/2026"
          ports:
            - containerPort: 25565
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: "6Gi"
            limits:
              memory: "7Gi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minecraft-disneybros-pvc
