apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-disneybros-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: minecraft-disneybros-pv
  resources:
    requests:
      storage: 35Gi
