apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: second-star-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: second-star-postgres-pv
  resources:
    requests:
      storage: 10Gi
